---
- hosts: database
  become: true

  vars_files:
    - vars/wordpress.yml
#    - vars/wordpress_vault.yml

  roles:
    - { role: ping,         tags: [ping] }
    - { role: mysql_client, tags: [mysql_client, mysql] }
    - { role: mysql_server, tags: [mysql_server, mysql] }
