---

- hosts: all
  become: true
  vars_files:
    - vars/wordpress.yml
    - vars/wordpress_vault.yml

  roles:
    - { role: nginx, tags: [nginx] }
    - { role: mysql, tags: [mysql] }
    - { role: php, tags: [php] }
    - { role: wordpress, tags: [wordpress, app] }

  post_tasks:
  - name: restart php
    systemd:
      name: php{{php_version}}-fpm
      state: restarted
      enabled: true

  - name: restart nginx
    systemd:
      name: nginx
      state: restarted
      enabled: true
